name: Build and deploy to Firebase

on:
  push:
    branches:
      - master
jobs:
  build-deploy:
    name: Build/Deploy job
    runs-on: ubuntu-18.04
    steps:
      - name: Downloading workflow dependencies
        uses: actions/checkout@master
      - uses: subosito/flutter-action@v1.3.0
        with:
          flutter-version: '1.17.x'
          channel: 'beta'
      
      - name: Downloading Flutter dependencies 
        run: flutter pub get

      - name: Enable Flutter for web
        run: flutter config --enable-web

      - name: Building app
        run: flutter build web

      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}